// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRfKpgQ_BHHB9WTsiudCJ7olp2XhAQ8i0',
    appId: '1:316106792961:web:ce35ed004ce464d4d1a000',
    messagingSenderId: '316106792961',
    projectId: 'deal-dash-7825b',
    authDomain: 'deal-dash-7825b.firebaseapp.com',
    storageBucket: 'deal-dash-7825b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQq704fLPkyPT-szCK9ZYz8oU4bqVFgB4',
    appId: '1:316106792961:android:6a1904d23a537d48d1a000',
    messagingSenderId: '316106792961',
    projectId: 'deal-dash-7825b',
    storageBucket: 'deal-dash-7825b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCaydiOrcDTqgr7ObPifXfFTmdEUq39DU',
    appId: '1:316106792961:ios:af9c40ff842280a2d1a000',
    messagingSenderId: '316106792961',
    projectId: 'deal-dash-7825b',
    storageBucket: 'deal-dash-7825b.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCaydiOrcDTqgr7ObPifXfFTmdEUq39DU',
    appId: '1:316106792961:ios:f03edc0ca57c8666d1a000',
    messagingSenderId: '316106792961',
    projectId: 'deal-dash-7825b',
    storageBucket: 'deal-dash-7825b.appspot.com',
    iosBundleId: 'com.example.eCommerceApp.RunnerTests',
  );
}
